upgrade circle-ci by using ramdisk

diff --git a/dev/lifecycle/package b/dev/lifecycle/package
--- a/dev/lifecycle/package
+++ b/dev/lifecycle/package
@@ -5,23 +5,24 @@ trap exit INT TERM
 
 ################################################################################
 
-TARGET_ARCHITECTURE="linux/amd64"
-TARGET_PACKAGE=""
+ARCH="amd64"
+PLATFORM="linux"
+SOURCE=""
 OUTPUT=""
 while [ $# -gt 0 ] ; do
 key="$1"
 case $key in
-  --arch)   TARGET_ARCHITECTURE="$2"; shift; shift; ;;
-  --pkg)    TARGET_PACKAGE="$2";      shift; shift; ;;
-  --output) OUTPUT="$2";              shift; shift; ;;
-  *)                                  shift;        ;;
+  --arch)   ARCH=${2#*/}; PLATFORM=${2%%/*}; shift; shift; ;;
+  --source) SOURCE="$2";                     shift; shift; ;;
+  --output) OUTPUT="$2";                     shift; shift; ;;
+  *)                                         shift;        ;;
 esac
 done
 
 ################################################################################
 
-if [ -z "${TARGET_PACKAGE}" ] ; then
-  (>&2 echo "[error] target package not provided")
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "[error] source package not provided")
   exit 1
 fi
 
@@ -29,6 +30,9 @@ if [ -z "${OUTPUT}" ] ; then
   (>&2 echo "[error] output not provided")
   exit 1
 fi
+
+
+OUTPUT_FILE=${OUTPUT}/$(basename ${SOURCE})-${PLATFORM}-${ARCH}
 
 ################################################################################
 
@@ -38,11 +42,16 @@ lifecycle::scala::pack() {
     return
   fi
 
-  local arch=${TARGET_ARCHITECTURE#*/}
-  local platform=${TARGET_ARCHITECTURE%%/*}
-  local output=${OUTPUT}/${TARGET_PACKAGE}-${platform}-${arch}
+  local output="$2"
+  if [ -z ${output} ] ; then
+    return
+  fi
 
-  echo "[info] (${platform}/${arch}) packaging ${TARGET_PACKAGE}"
+  if [ -f ${output} ] ; then
+    rm -f ${output}
+  fi
+
+
   cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy pack
 
   if [ -f ${output} ] ; then
@@ -52,13 +61,14 @@ lifecycle::scala::pack() {
   cp -R ${dir}/target/pack/bin ${output}
   cp -R ${dir}/target/pack/lib ${output}
 
-  echo "[info] (${platform}/${arch}) check"
-  du -hs ${output}
+  echo "[info] ${output} packed"
 
-  echo "[info] (${platform}/${arch}) done"
+  du -hs ${output}
 }
+
 
 ################################################################################
 
 lifecycle::scala::pack \
-  /project/services/${TARGET_PACKAGE}
+  ${SOURCE} \
+  ${OUTPUT_FILE}
diff --git a/dev/lifecycle/sync b/dev/lifecycle/sync
--- a/dev/lifecycle/sync
+++ b/dev/lifecycle/sync
@@ -5,19 +5,19 @@ trap exit INT TERM
 
 ################################################################################
 
-TARGET_PACKAGE=""
+SOURCE=""
 while [ $# -gt 0 ] ; do
 key="$1"
 case $key in
-  --pkg)  TARGET_PACKAGE="$2";  shift; shift; ;;
-  *)                            shift;        ;;
+  --source)  SOURCE="$2";  shift; shift; ;;
+  *)                       shift;        ;;
 esac
 done
 
 ################################################################################
 
-if [ -z "${TARGET_PACKAGE}" ] ; then
-  (>&2 echo "[error] target package not provided")
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "[error] source package not provided")
   exit 1
 fi
 
@@ -29,6 +29,14 @@ lifecycle::scala::sync() {
     return
   fi
 
+  if [ -d ${dir}/vendor ] ; then
+    rm -rf ${dir}/vendor
+  fi
+
+  if [ -f ${dir}/go.sum ] ; then
+    rm -f ${dir}/go.sum
+  fi
+
   cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy clean
   cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy update
   cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy evicted
@@ -37,4 +45,4 @@ lifecycle::scala::sync() {
 ################################################################################
 
 lifecycle::scala::sync \
-  /project/services/${TARGET_PACKAGE}
+  ${SOURCE}
