upgrade circle-ci by using ramdisk

diff --git a/dev/lifecycle/test b/dev/lifecycle/test
--- a/dev/lifecycle/test
+++ b/dev/lifecycle/test
@@ -5,21 +5,21 @@ trap exit INT TERM
 
 ################################################################################
 
-TARGET_PACKAGE=""
+SOURCE=""
 OUTPUT=""
 while [ $# -gt 0 ] ; do
 key="$1"
 case $key in
-  --pkg)    TARGET_PACKAGE="$2";  shift; shift; ;;
-  --output) OUTPUT="$2";          shift; shift; ;;
-  *)                              shift;        ;;
+  --source) SOURCE="$2";  shift; shift; ;;
+  --output) OUTPUT="$2";  shift; shift; ;;
+  *)                      shift;        ;;
 esac
 done
 
 ################################################################################
 
-if [ -z "${TARGET_PACKAGE}" ] ; then
-  (>&2 echo "[error] target package not provided")
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "[error] source package not provided")
   exit 1
 fi
 
@@ -35,7 +35,13 @@ lifecycle::scala::test() {
   if [ -z ${dir} -o ! -d ${dir} ] ; then
     return
   fi
-  local output="$2"
+  #local output="$2"
+  #local target=$(basename $dir)
+
+  #coverage_out=$(tempfile)
+  #test_out=$(tempfile)
+
+  #mkdir -p ${output}
 
   cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy test
 }
@@ -43,5 +49,5 @@ lifecycle::scala::test() {
 ################################################################################
 
 lifecycle::scala::test \
-  /project/services/${TARGET_PACKAGE} \
-  ${OUTPUT}/unit-tests
+  ${SOURCE} \
+  ${OUTPUT}
